# Generated by Django 5.1.3 on 2024-11-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
