# Generated by Django 5.1.3 on 2024-11-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0002_remove_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='type_room',
        ),
    ]
