# Generated by Django 5.1.3 on 2024-11-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0003_remove_program_type_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.CharField(default='ничего', max_length=200, verbose_name='Описание'),
        ),
    ]
