# Generated by Django 5.1.3 on 2024-11-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0011_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='media/mask', null=True, upload_to='media/'),
        ),
    ]
