# Generated by Django 5.1.3 on 2024-11-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0012_alter_room_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'комнаты'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='program',
            name='briefly_description',
            field=models.CharField(max_length=1200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.IntegerField(null=True, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='media/mask', upload_to='media/'),
        ),
    ]
