# Generated by Django 5.1.3 on 2024-11-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0013_alter_program_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(default='None', max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
