# Generated by Django 5.1.3 on 2024-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0014_alter_program_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='brify_description',
            field=models.CharField(default='кр опис', max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='briefly_description',
            field=models.CharField(default='Краткое описание', max_length=1200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(default='Тут будет описание', max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
