# Generated by Django 5.1.3 on 2024-11-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0015_type_brify_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_order',
            field=models.BooleanField(default=False, verbose_name='занят'),
        ),
    ]
