# Generated by Django 5.1.3 on 2024-12-03 07:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0016_room_is_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='День заселения')),
                ('date_out', models.DateField(default=datetime.date(2000, 2, 1), verbose_name='День выселения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость')),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sanatorium.program', verbose_name='Название программы')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sanatorium.room', verbose_name='Номер комнаты')),
            ],
        ),
    ]
