# Generated by Django 5.1.3 on 2024-12-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0018_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_out',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_in',
        ),
        migrations.RemoveField(
            model_name='users',
            name='program',
        ),
        migrations.RemoveField(
            model_name='users',
            name='room',
        ),
    ]
