# Generated by Django 5.1.3 on 2024-12-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanatorium', '0019_remove_users_date_in_remove_users_date_out_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Заказы'},
        ),
    ]
