# Generated by Django 5.1.3 on 2024-11-11 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('Last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('Middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата рождения')),
                ('Date_in', models.DateField(auto_now_add=True, verbose_name='Дата заселения')),
                ('Date_go', models.DateField(verbose_name='Дата выезда')),
                ('Date_update', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('is_user', models.BooleanField(default=True, verbose_name='Заселен')),
            ],
        ),
    ]
